// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiff2ve4UnqeUfG73CmP6V47lQHWloSA',
    appId: '1:709678945324:web:3352d09fb627cd0ab7ed89',
    messagingSenderId: '709678945324',
    projectId: 'sukabumi-one-access-app-c7f15',
    authDomain: 'sukabumi-one-access-app-c7f15.firebaseapp.com',
    storageBucket: 'sukabumi-one-access-app-c7f15.firebasestorage.app',
    measurementId: 'G-9BH8RDCLRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1n-_fvGdfTJYLvCOp438rlEAfCVuloyU',
    appId: '1:709678945324:android:83857869c836e35db7ed89',
    messagingSenderId: '709678945324',
    projectId: 'sukabumi-one-access-app-c7f15',
    storageBucket: 'sukabumi-one-access-app-c7f15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADA0dl4WKlbcDueTN9ktnHV5ZjG1VvZoI',
    appId: '1:709678945324:ios:641afd317a3c4c38b7ed89',
    messagingSenderId: '709678945324',
    projectId: 'sukabumi-one-access-app-c7f15',
    storageBucket: 'sukabumi-one-access-app-c7f15.firebasestorage.app',
    iosBundleId: 'com.diskominfo.mobile',
  );
}
